name: Deploy

on: [pull_request]

jobs:
  build:
    name: say hello
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
    - run: npm ci
    - run: npm run build
